version: "3.8"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - $(pwd)/ha_server_data/mosquitto/config:/mosquitto/config:rw
      - $(pwd)/ha_server_data/mosquitto/data:/mosquitto/data:rw
      - $(pwd)/ha_server_data/mosquitto/log:/mosquitto/log:rw

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    devices:
      - "/dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6ab65cf94898ec11aed49fd044d80d13-if00-port0:/dev/ttyACM0"
    ports:
      - 8081:8080
    volumes:
      - $(pwd)/ha_server_data/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - mqtt

  zigbee2mqtt_2:
    container_name: zigbee2mqtt_2
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    devices:
      - "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_c26e809bff93eb11a2dfb15b3d98b6d1-if00-port0:/dev/ttyACM0"
    ports:
      - 8082:8080
    volumes:
      - $(pwd)/ha_server_data/zigbee2mqtt_2/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - mqtt

  webthings-gateway:
    container_name: webthings-gateway
    image: webthingsio/gateway:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "4443:4443"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - $(pwd)/ha_server_data/webthings:/home/node/.webthings
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "1880:1880"
    volumes:
      - $(pwd)/ha_server_data/nodered:/data

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=sensors_data
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors_data
    volumes:      
      - $(pwd)/ha_server_data/influx/data:/var/lib/influxdb2
      - $(pwd)/ha_server_data/influx/config/config.yml:/etc/influxdb2/config.yml
    ports:
      - "8086:8086"
    
    
      
