version: "3.8"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - $(pwd)/ha_server_data/mosquitto/config:/mosquitto/config:rw
      - $(pwd)/ha_server_data/mosquitto/data:/mosquitto/data:rw
      - $(pwd)/ha_server_data/mosquitto/log:/mosquitto/log:rw

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    networks:
      - internal
    restart: unless-stopped
    devices:
      - ${Z2M_DEV:?required}:/dev/ttyACM0
    ports:
      - 8081:8080
    volumes:
      - $(pwd)/ha_server_data/zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - mqtt

  zigbee2mqtt_2:
    container_name: zigbee2mqtt_2
    image: koenkk/zigbee2mqtt
    networks:
      - internal
    restart: unless-stopped
    devices:      
      - ${Z2M_2_DEV:?required}:/dev/ttyACM0
    ports:
      - 8082:8080
    volumes:
      - $(pwd)/ha_server_data/zigbee2mqtt_2/data:/app/data
      - /run/udev:/run/udev:ro
    environment:
      - TZ=Europe/Warsaw
    depends_on:
      - mqtt

  webthings-gateway:
    container_name: webthings-gateway
    image: webthingsio/gateway:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "8080:8080"
      - "4443:4443"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - $(pwd)/ha_server_data/webthings:/home/node/.webthings
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    restart: unless-stopped
    networks:
      - internal
    environment:
      - TZ=Europe/Warsaw
    ports:
      - "1880:1880"
    volumes:
      - $(pwd)/ha_server_data/nodered:/data

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    restart: unless-stopped
    networks:
      - internal
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:?required}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:?required}
      - DOCKER_INFLUXDB_INIT_ORG=sensors_data
      - DOCKER_INFLUXDB_INIT_BUCKET=sensors_data
    volumes:      
      - $(pwd)/ha_server_data/influx/data:/var/lib/influxdb2
      - $(pwd)/ha_server_data/influx/config/config.yml:/etc/influxdb2/config.yml
    ports:
      - "8086:8086"

  mdns-reflector:
    container_name: mdns-reflector
    image: flungo/avahi
    restart: unless-stopped
    environment:
      - REFLECTOR_ENABLE_REFLECTOR=yes
    networks:
      internal:
      physical:
        # ipv4_address: 10.0.0.10



networks:
  internal:
    name: internal
    driver: bridge

  physical:
    name: physical
    driver: macvlan
    driver_opts:
      parent: ${HOST_PHY_INTERFACE:?required}
    ipam:
      config:
        - subnet: "10.0.0.0/24"
          gateway: "10.0.0.1"

    
    
      
